# -*- coding: utf-8 -*-
"""sf-crime-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GDhsM5gXM5ejhPormODckqR77pspaRW

# Crime classification using supervised machine learning in San Francisco

Se están corriendo 1000 samples ya que el ram de la sesión se consume rápido.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report

train_dataset_filename = 'train.csv'
test_dataset_filename = 'test.csv'

train_df = pd.read_csv(train_dataset_filename).head(1000)
train_df

test_df = pd.read_csv(test_dataset_filename).head(1000)
test_df

train_df.info()

train_df.isnull().sum()

train_df['Category'].value_counts()

top_crimes = train_df['Category'].value_counts().head(10)

plt.figure(figsize=(12, 5))
top_crimes.plot(kind='bar')
plt.title('Top 10 Categorías de Crimen')
plt.xlabel('Categoría')
plt.ylabel('Cantidad')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

train_df['DayOfWeek'].value_counts().plot(kind='bar', figsize=(8, 4), title='Crímenes por Día de la Semana')
plt.tight_layout()
plt.show()

train_df['PdDistrict'].value_counts().plot(kind='bar', figsize=(8, 4), title='Crímenes por Distrito')
plt.tight_layout()
plt.show()

from sklearn.preprocessing import LabelEncoder

# Extraer features de la fecha
train_df['Dates'] = pd.to_datetime(train_df['Dates'])
train_df['Hour'] = train_df['Dates'].dt.hour
train_df['Month'] = train_df['Dates'].dt.month
train_df['Year'] = train_df['Dates'].dt.year

# Encodear variables categóricas
le_day = LabelEncoder()
le_district = LabelEncoder()
le_category = LabelEncoder()

train_df['DayOfWeek_enc'] = le_day.fit_transform(train_df['DayOfWeek'])
train_df['PdDistrict_enc'] = le_district.fit_transform(train_df['PdDistrict'])
train_df['Category_enc'] = le_category.fit_transform(train_df['Category'])

train_df.head()

from sklearn.model_selection import train_test_split

features = ['X', 'Y', 'Hour', 'Month', 'Year', 'DayOfWeek_enc', 'PdDistrict_enc']

X = train_df[features]
y = train_df['Category_enc']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Train size: {X_train.shape}")
print(f"Test size: {X_test.shape}")

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model_lr = LogisticRegression(max_iter=1000, random_state=42)
model_lr.fit(X_train, y_train)

y_pred_lr = model_lr.predict(X_test)
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")

from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(max_depth=20, random_state=42)
model_dt.fit(X_train, y_train)

y_pred_dt = model_dt.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print(f"Decision Tree Accuracy: {accuracy_dt:.4f}")

from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators=100, max_depth=20, random_state=42, n_jobs=-1)
model_rf.fit(X_train, y_train)

y_pred_rf = model_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf:.4f}")

from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score

# Usamos el mejor modelo (Random Forest)
y_pred = y_pred_rf

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

cm = confusion_matrix(y_test, y_pred)
print(cm)

precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
print(precision)

recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
print(recall)

labels_presentes = np.unique(y_test)
nombres_presentes = le_category.classes_[labels_presentes]

report = classification_report(y_test, y_pred, labels=labels_presentes, target_names=nombres_presentes, zero_division=0)
print(report)

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_score,
    recall_score,
    classification_report
)

resultados = {
    'Logistic Regression': accuracy_lr,
    'Decision Tree': accuracy_dt,
    'Random Forest': accuracy_rf
}

plt.figure(figsize=(8, 4))
plt.bar(resultados.keys(), resultados.values(), color=['steelblue', 'orange', 'green'])
plt.title('Comparación de Accuracy por Modelo')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
for i, (k, v) in enumerate(resultados.items()):
    plt.text(i, v + 0.01, f"{v:.4f}", ha='center')
plt.tight_layout()
plt.show()

from sklearn.metrics import ConfusionMatrixDisplay
import numpy as np

labels_presentes = np.unique(y_test)
nombres_presentes = le_category.classes_[labels_presentes]

cm = confusion_matrix(y_test, y_pred, labels=labels_presentes)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=nombres_presentes
)

fig, ax = plt.subplots(figsize=(18, 18))
disp.plot(ax=ax, xticks_rotation=90)
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
print(precision)

recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
print(recall)

"""## Conclusiones

1. **El dataset está muy desbalanceado.** Las categorías `LARCENY/THEFT` y `OTHER OFFENSES` representan la mayor parte de los crímenes en San Francisco, lo que sesga los modelos hacia predecir estas clases con más frecuencia.

2. **La ubicación geográfica (X, Y) y la hora son los features más importantes.** Los crímenes no ocurren aleatoriamente — ciertos distritos y horarios tienen patrones de criminalidad muy marcados que los modelos de árbol logran capturar bien.

3. **Random Forest supera a Logistic Regression y Decision Tree.** Al combinar múltiples árboles, el modelo reduce el overfitting y captura mejor la complejidad de las 39 categorías de crimen. Sin embargo, predecir 39 clases con alta precisión sigue siendo un reto, y técnicas adicionales como boosting o feature engineering más profundo podrían mejorar el resultado.
"""